<?php
// Each entry: 'Full Currency Name' => ['code' => 'ISO-4217', 'symbol' => '...']
// Sorted alphabetically by full name.
// Symbol is used for display; code is stored in the s_currency column.
$currencies = array(
	'Afghan Afghani'                    => ['code' => 'AFN',  'symbol' => '&#1547;'],
	'Albanian Lek'                      => ['code' => 'ALL',  'symbol' => 'L'],
	'Algerian Dinar'                    => ['code' => 'DZD',  'symbol' => 'دج'],
	'Angolan Kwanza'                    => ['code' => 'AOA',  'symbol' => 'Kz'],
	'Argentine Peso'                    => ['code' => 'ARS',  'symbol' => '&#36;'],
	'Armenian Dram'                     => ['code' => 'AMD',  'symbol' => '&#1423;'],
	'Aruban Florin'                     => ['code' => 'AWG',  'symbol' => '&#402;'],
	'Australian Dollar'                 => ['code' => 'AUD',  'symbol' => 'A&#36;'],
	'Azerbaijani Manat'                 => ['code' => 'AZN',  'symbol' => '&#8371;'],
	'Bahamian Dollar'                   => ['code' => 'BSD',  'symbol' => 'B&#36;'],
	'Bahraini Dinar'                    => ['code' => 'BHD',  'symbol' => '&#1583;.&#1576;'],
	'Bangladeshi Taka'                  => ['code' => 'BDT',  'symbol' => '&#2547;'],
	'Barbadian Dollar'                  => ['code' => 'BBD',  'symbol' => 'Bds&#36;'],
	'Belarusian Ruble'                  => ['code' => 'BYN',  'symbol' => 'Br'],
	'Belize Dollar'                     => ['code' => 'BZD',  'symbol' => 'BZ&#36;'],
	'Bermudian Dollar'                  => ['code' => 'BMD',  'symbol' => 'BD&#36;'],
	'Bhutanese Ngultrum'                => ['code' => 'BTN',  'symbol' => 'Nu'],
	'Bolivian Boliviano'                => ['code' => 'BOB',  'symbol' => 'Bs.'],
	'Bosnia-Herzegovina Mark'           => ['code' => 'BAM',  'symbol' => 'KM'],
	'Botswana Pula'                     => ['code' => 'BWP',  'symbol' => 'P'],
	'Brazilian Real'                    => ['code' => 'BRL',  'symbol' => 'R&#36;'],
	'British Pound'                     => ['code' => 'GBP',  'symbol' => '&#163;'],
	'Brunei Dollar'                     => ['code' => 'BND',  'symbol' => 'B&#36;'],
	'Bulgarian Lev'                     => ['code' => 'BGN',  'symbol' => '&#1083;&#1074;'],
	'Burundian Franc'                   => ['code' => 'BIF',  'symbol' => 'Fr'],
	'Canadian Dollar'                   => ['code' => 'CAD',  'symbol' => 'CA&#36;'],
	'Cape Verdean Escudo'               => ['code' => 'CVE',  'symbol' => '&#36;'],
	'Cayman Islands Dollar'             => ['code' => 'KYD',  'symbol' => 'CI&#36;'],
	'Central African CFA Franc'         => ['code' => 'XAF',  'symbol' => 'Fr'],
	'CFP Franc'                         => ['code' => 'XPF',  'symbol' => 'Fr'],
	'Chilean Peso'                      => ['code' => 'CLP',  'symbol' => '&#36;'],
	'Chinese Yuan'                      => ['code' => 'CNY',  'symbol' => '&#165;'],
	'Colombian Peso'                    => ['code' => 'COP',  'symbol' => '&#36;'],
	'Comorian Franc'                    => ['code' => 'KMF',  'symbol' => 'Fr'],
	'Congolese Franc'                   => ['code' => 'CDF',  'symbol' => 'Fr'],
	'Costa Rican Colón'                 => ['code' => 'CRC',  'symbol' => '&#8353;'],
	'Croatian Kuna'                     => ['code' => 'HRK',  'symbol' => 'kn'],
	'Cuban Peso'                        => ['code' => 'CUP',  'symbol' => '&#36;'],
	'Czech Koruna'                      => ['code' => 'CZK',  'symbol' => 'K&#269;'],
	'Danish Krone'                      => ['code' => 'DKK',  'symbol' => 'kr'],
	'Djiboutian Franc'                  => ['code' => 'DJF',  'symbol' => 'Fr'],
	'Dominican Peso'                    => ['code' => 'DOP',  'symbol' => 'RD&#36;'],
	'East Caribbean Dollar'             => ['code' => 'XCD',  'symbol' => 'EC&#36;'],
	'Egyptian Pound'                    => ['code' => 'EGP',  'symbol' => '&#163;'],
	'Eritrean Nakfa'                    => ['code' => 'ERN',  'symbol' => 'Nfk'],
	'Ethiopian Birr'                    => ['code' => 'ETB',  'symbol' => 'Br'],
	'Euro'                              => ['code' => 'EUR',  'symbol' => '&#8364;'],
	'Falkland Islands Pound'            => ['code' => 'FKP',  'symbol' => '&#163;'],
	'Fijian Dollar'                     => ['code' => 'FJD',  'symbol' => 'FJ&#36;'],
	'Gambian Dalasi'                    => ['code' => 'GMD',  'symbol' => 'D'],
	'Georgian Lari'                     => ['code' => 'GEL',  'symbol' => '&#8382;'],
	'Ghanaian Cedi'                     => ['code' => 'GHS',  'symbol' => 'GH&#162;'],
	'Gibraltar Pound'                   => ['code' => 'GIP',  'symbol' => '&#163;'],
	'Guatemalan Quetzal'                => ['code' => 'GTQ',  'symbol' => 'Q'],
	'Guinean Franc'                     => ['code' => 'GNF',  'symbol' => 'Fr'],
	'Guyanese Dollar'                   => ['code' => 'GYD',  'symbol' => 'G&#36;'],
	'Haitian Gourde'                    => ['code' => 'HTG',  'symbol' => 'G'],
	'Honduran Lempira'                  => ['code' => 'HNL',  'symbol' => 'L'],
	'Hong Kong Dollar'                  => ['code' => 'HKD',  'symbol' => 'HK&#36;'],
	'Hungarian Forint'                  => ['code' => 'HUF',  'symbol' => 'Ft'],
	'Icelandic Króna'                   => ['code' => 'ISK',  'symbol' => 'kr'],
	'Indian Rupee'                      => ['code' => 'INR',  'symbol' => '&#8377;'],
	'Indonesian Rupiah'                 => ['code' => 'IDR',  'symbol' => 'Rp'],
	'Iranian Rial'                      => ['code' => 'IRR',  'symbol' => '&#65020;'],
	'Iraqi Dinar'                       => ['code' => 'IQD',  'symbol' => '&#1593;.&#1583;'],
	'Israeli New Shekel'                => ['code' => 'ILS',  'symbol' => '&#8362;'],
	'Jamaican Dollar'                   => ['code' => 'JMD',  'symbol' => 'J&#36;'],
	'Japanese Yen'                      => ['code' => 'JPY',  'symbol' => '&#165;'],
	'Jordanian Dinar'                   => ['code' => 'JOD',  'symbol' => '&#1583;.&#1575;'],
	'Kazakhstani Tenge'                 => ['code' => 'KZT',  'symbol' => '&#8376;'],
	'Kenyan Shilling'                   => ['code' => 'KES',  'symbol' => 'KSh'],
	'Kuwaiti Dinar'                     => ['code' => 'KWD',  'symbol' => '&#1583;.&#1603;'],
	'Kyrgystani Som'                    => ['code' => 'KGS',  'symbol' => '&#1083;&#1074;'],
	'Lao Kip'                           => ['code' => 'LAK',  'symbol' => '&#8365;'],
	'Lebanese Pound'                    => ['code' => 'LBP',  'symbol' => '&#163;'],
	'Lesotho Loti'                      => ['code' => 'LSL',  'symbol' => 'L'],
	'Liberian Dollar'                   => ['code' => 'LRD',  'symbol' => 'L&#36;'],
	'Libyan Dinar'                      => ['code' => 'LYD',  'symbol' => 'LD'],
	'Macanese Pataca'                   => ['code' => 'MOP',  'symbol' => 'P'],
	'Macedonian Denar'                  => ['code' => 'MKD',  'symbol' => '&#1076;&#1077;&#1085;'],
	'Malagasy Ariary'                   => ['code' => 'MGA',  'symbol' => 'Ar'],
	'Malawian Kwacha'                   => ['code' => 'MWK',  'symbol' => 'MK'],
	'Malaysian Ringgit'                 => ['code' => 'MYR',  'symbol' => 'RM'],
	'Maldivian Rufiyaa'                 => ['code' => 'MVR',  'symbol' => 'Rf'],
	'Mauritanian Ouguiya'               => ['code' => 'MRU',  'symbol' => 'UM'],
	'Mauritian Rupee'                   => ['code' => 'MUR',  'symbol' => '&#8360;'],
	'Mexican Peso'                      => ['code' => 'MXN',  'symbol' => '&#36;'],
	'Moldovan Leu'                      => ['code' => 'MDL',  'symbol' => 'L'],
	'Mongolian Tögrög'                  => ['code' => 'MNT',  'symbol' => '&#8366;'],
	'Moroccan Dirham'                   => ['code' => 'MAD',  'symbol' => 'MAD'],
	'Mozambican Metical'                => ['code' => 'MZN',  'symbol' => 'MT'],
	'Myanmar Kyat'                      => ['code' => 'MMK',  'symbol' => 'K'],
	'Namibian Dollar'                   => ['code' => 'NAD',  'symbol' => 'N&#36;'],
	'Nepalese Rupee'                    => ['code' => 'NPR',  'symbol' => '&#8360;'],
	'Netherlands Antillean Guilder'     => ['code' => 'ANG',  'symbol' => '&#402;'],
	'New Taiwan Dollar'                 => ['code' => 'TWD',  'symbol' => 'NT&#36;'],
	'New Zealand Dollar'                => ['code' => 'NZD',  'symbol' => 'NZ&#36;'],
	'Nicaraguan Córdoba'                => ['code' => 'NIO',  'symbol' => 'C&#36;'],
	'Nigerian Naira'                    => ['code' => 'NGN',  'symbol' => '&#8358;'],
	'North Korean Won'                  => ['code' => 'KPW',  'symbol' => '&#8361;'],
	'Norwegian Krone'                   => ['code' => 'NOK',  'symbol' => 'kr'],
	'Omani Rial'                        => ['code' => 'OMR',  'symbol' => '&#65020;'],
	'Pakistani Rupee'                   => ['code' => 'PKR',  'symbol' => '&#8360;'],
	'Panamanian Balboa'                 => ['code' => 'PAB',  'symbol' => 'B/.'],
	'Papua New Guinean Kina'            => ['code' => 'PGK',  'symbol' => 'K'],
	'Paraguayan Guaraní'                => ['code' => 'PYG',  'symbol' => '&#8370;'],
	'Peruvian Sol'                      => ['code' => 'PEN',  'symbol' => 'S/.'],
	'Philippine Peso'                   => ['code' => 'PHP',  'symbol' => '&#8369;'],
	'Polish Zloty'                      => ['code' => 'PLN',  'symbol' => 'z&#322;'],
	'Qatari Riyal'                      => ['code' => 'QAR',  'symbol' => '&#65020;'],
	'Romanian Leu'                      => ['code' => 'RON',  'symbol' => 'lei'],
	'Russian Ruble'                     => ['code' => 'RUB',  'symbol' => '&#8381;'],
	'Rwandan Franc'                     => ['code' => 'RWF',  'symbol' => 'RF'],
	'Samoan Tālā'                       => ['code' => 'WST',  'symbol' => 'T'],
	'São Tomé & Príncipe Dobra'         => ['code' => 'STN',  'symbol' => 'Db'],
	'Saudi Riyal'                       => ['code' => 'SAR',  'symbol' => '&#65020;'],
	'Serbian Dinar'                     => ['code' => 'RSD',  'symbol' => 'din'],
	'Seychellois Rupee'                 => ['code' => 'SCR',  'symbol' => '&#8360;'],
	'Sierra Leonean Leone'              => ['code' => 'SLL',  'symbol' => 'Le'],
	'Singapore Dollar'                  => ['code' => 'SGD',  'symbol' => 'S&#36;'],
	'Solomon Islands Dollar'            => ['code' => 'SBD',  'symbol' => 'SI&#36;'],
	'Somali Shilling'                   => ['code' => 'SOS',  'symbol' => 'Sh'],
	'South African Rand'                => ['code' => 'ZAR',  'symbol' => 'R'],
	'South Korean Won'                  => ['code' => 'KRW',  'symbol' => '&#8361;'],
	'South Sudanese Pound'              => ['code' => 'SSP',  'symbol' => '&#163;'],
	'Sri Lankan Rupee'                  => ['code' => 'LKR',  'symbol' => '&#8360;'],
	'Sudanese Pound'                    => ['code' => 'SDG',  'symbol' => '&#163;'],
	'Surinamese Dollar'                 => ['code' => 'SRD',  'symbol' => 'SR&#36;'],
	'Swazi Lilangeni'                   => ['code' => 'SZL',  'symbol' => 'L'],
	'Swedish Krona'                     => ['code' => 'SEK',  'symbol' => 'kr'],
	'Swiss Franc'                       => ['code' => 'CHF',  'symbol' => 'Fr'],
	'Syrian Pound'                      => ['code' => 'SYP',  'symbol' => '&#163;'],
	'Taiwanese Dollar'                  => ['code' => 'TWD',  'symbol' => 'NT&#36;'],
	'Tajikistani Somoni'                => ['code' => 'TJS',  'symbol' => 'SM'],
	'Tanzanian Shilling'                => ['code' => 'TZS',  'symbol' => 'TSh'],
	'Thai Baht'                         => ['code' => 'THB',  'symbol' => '&#3647;'],
	'Tongan Paʻanga'                    => ['code' => 'TOP',  'symbol' => 'T&#36;'],
	'Trinidad & Tobago Dollar'          => ['code' => 'TTD',  'symbol' => 'TT&#36;'],
	'Tunisian Dinar'                    => ['code' => 'TND',  'symbol' => 'DT'],
	'Turkmenistani Manat'               => ['code' => 'TMT',  'symbol' => 'T'],
	'Turkish Lira'                      => ['code' => 'TRY',  'symbol' => '&#8378;'],
	'UAE Dirham'                        => ['code' => 'AED',  'symbol' => '&#1583;.&#1573;'],
	'Ugandan Shilling'                  => ['code' => 'UGX',  'symbol' => 'USh'],
	'Ukrainian Hryvnia'                 => ['code' => 'UAH',  'symbol' => '&#8372;'],
	'Uruguayan Peso'                    => ['code' => 'UYU',  'symbol' => '&#36;U'],
	'US Dollar'                         => ['code' => 'USD',  'symbol' => '&#36;'],
	'Uzbekistani Sum'                   => ['code' => 'UZS',  'symbol' => '&#1083;&#1074;'],
	'Vanuatu Vatu'                      => ['code' => 'VUV',  'symbol' => 'Vt'],
	'Venezuelan Bolívar'                => ['code' => 'VES',  'symbol' => 'Bs.S'],
	'Vietnamese Dong'                   => ['code' => 'VND',  'symbol' => '&#8363;'],
	'West African CFA Franc'            => ['code' => 'XOF',  'symbol' => 'Fr'],
	'Yemeni Rial'                       => ['code' => 'YER',  'symbol' => '&#65020;'],
	'Zambian Kwacha'                    => ['code' => 'ZMW',  'symbol' => 'ZK'],
	'Zimbabwean Dollar'                 => ['code' => 'ZWL',  'symbol' => 'Z&#36;'],

	// ── Cryptocurrencies ─────────────────────────────────────────────
	'Bitcoin'                           => ['code' => 'BTC',  'symbol' => 'BTC'],
	'Ethereum'                          => ['code' => 'ETH',  'symbol' => 'ETH'],
	'Tether'                            => ['code' => 'USDT', 'symbol' => 'USDT'],
);
?>
